name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to the `main` branch (change to `master` if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'  # Set the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app
      - name: Build the app
        run: npm run build

      # Deploy the app to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
